a= imread('wajah.jpg');imshow(a);
b= imread('pemandangan.jpg');imshow(b);
c= imread('sidik jari.jpg');imshow(c);
d=rgb2gray(a);
e=rgb2gray(b);
f=rgb2gray(c);
Gambar1 = edge(d,'roberts');
Gambar2 = edge(d,'sobel');
Gambar3 = edge(d,'prewitt');
Gambar4 = edge(e,'roberts');
Gambar5 = edge(e,'sobel');
Gambar6 = edge(e,'prewitt');
Gambar7 = edge(f,'roberts');
Gambar8 = edge(f,'sobel');
Gambar9 = edge(f,'prewitt');
subplot(3,4,1);imshow(a);title('Gambar Wajah');
subplot(3,4,2);imshow(Gambar1);title('Gambar Wajah Convert Roberts');
subplot(3,4,3);imshow(Gambar2);title('Gambar Wajah Convert Sobel');
subplot(3,4,4);imshow(Gambar3);title('Gambar Wajah Convert Prewitt');
subplot(3,4,5);imshow(b);title('Gambar Pemandangan');
subplot(3,4,6);imshow(Gambar4);title('Gambar Pemandangan Convert Roberts');
subplot(3,4,7);imshow(Gambar5);title('Gambar Pemandangan Convert Sobel');
subplot(3,4,8);imshow(Gambar6);title('Gambar Pemandangan Convert Prewitt');
subplot(3,4,9);imshow(c);title('Gambar Sidik Jari');
subplot(3,4,10);imshow(Gambar7);title('Gambar Sidik Jari Convert Roberts');
subplot(3,4,11);imshow(Gambar8);title('Gambar Sidik Jari Convert Sobel');
subplot(3,4,12);imshow(Gambar9);title('Gambar Sidik Jari Convert Prewitt');
